global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'gatherlove-monitor'

scrape_configs:
  - job_name: 'spring_boot_app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['a03gatherlove.duckdns.org:8080']
        labels:
          application: 'gatherlove'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
